name: Code Vulnerability Scanning

on:
  push:
    branches: [develop]

  pull_request:
    branches: [develop]

  schedule:
    - cron: '0 6 * * 6'

jobs:
  analyze:
    name: Code Analysis
    uses: plantemoran-appdev/.github/.github/workflows/code-analysis-reuse.yml@develop
    with:
      languages: '["javascript"]'
