name: Pull Request Auto Assignment

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - review_request_removed
    branches:
      - develop

jobs:
  pull-request-assignment:
    name: Pull Request Auto Assignment
    uses: plantemoran-appdev/.github/.github/workflows/pull-request-assignment-reuse.yml@develop
    secrets:
      additional-access-pat: ${{ secrets.GH_ACTION_AUTO_ASSIGN_PAT }}
